### ISSUE TITLE
Access denied to folder

### ISSUE THREAD

**Issue by five0mustang12** [frogmorecs/RawPrint#10]
Get an error when using RawPrint to print a PDF from a folder on the local drive.  Permission and Attribute have been set correctly.  Error occurs stating: "Access  to the path 'C:\PDF' is denied.  Does RawPrint require different permissions?

Thank You
![image](https://user-images.githubusercontent.com/34655606/38638796-fa91a044-3d94-11e8-9030-d4f84d5023a2.png)

**Comment by tonyedgecombe** [comment]
The signature for PrintRawFile is:

`void PrintRawFile(string printer, string path, string documentName, bool paused = false);`

documentName is not the file name, it is the name of the document as it appears in the print queue.
