### ISSUE TITLE
Failed Print to Networkprinter

### ISSUE THREAD

**Issue by davidkurniawan1980** [frogmorecs/RawPrint#13]
this is mycode, Code no error and nothing happened
Imports RawPrint
Public Class Form1
    Dim cc As New printer
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        '  Myx.RunCommandCom("rawprint", """\\david-pc\LX310"" z.prn", True)
        cc.PrintRawFile("\\david-pc\lx310", "z.prn", True)

    End Sub
end class

**Comment by tonyedgecombe** [comment]
The final parameter to PrintRawFile should be False, otherwise it will just spool a paused job.
