### ISSUE TITLE
Problem printing £ sign using raw print

### ISSUE THREAD

**Issue by Collis88** [frogmorecs/RawPrint#17]
Hi i am having trouble printing the £ sign when using the rawprinter class, when i send a txt file to be printed it changes the £ symbol to ú.

Is there a way to get the pound sign to print correctly?

`  
Dim printer As IPrinter = New Printer()
printer.PrintRawFile("\\ROSSENDALEDC\Konica Colour", "c:\test\", "receipt.txt")
`
This gets printed as the below

test the ú sign prints

Thanks

**Comment by tonyedgecombe** [comment]
RawPrint isn't a text file printer, it doesn't have a concept of characters, just raw bytes.

**Comment by Collis88** [comment]
Ok thanks
