### ISSUE TITLE
virtual printer

### ISSUE THREAD

**Issue by yonbin** [frogmorecs/RawPrint#20]
Can send files directly to virtual printer?

**Comment by tonyedgecombe** [comment]
Yes, but not many virtual printers will do anything with a raw file.

**Comment by yonbin** [comment]
I want to print spl/pcl as a pdf via a virtual printer. Test can't output pdf。

**Comment by tonyedgecombe** [comment]
Well that won't work, Raw Print bypasses the printer driver so the output won't get rendered.

You need a PCL to PDF converter, there are a few commercial products around that do that.
