### ISSUE TITLE
Set up/change printer orientation and select paper type/size

### ISSUE THREAD

**Issue by uanumula** [frogmorecs/RawPrint#22]
Your code does not have functions or logic using Devmode to change the printer settings like orientation at run time from Portrait to Landscape and back and Setting up the paper size / type programmatically.

**Comment by tonyedgecombe** [comment]
No it doesn't.

The purpose of RawPrint is to bypass the printer driver, it allows you to send a raw print file directly to the printer and assumes that file will already have the required print setup codes embedded in it.
