### ISSUE TITLE
Print Image don't work 

### ISSUE THREAD

**Issue by urbanop** [frogmorecs/RawPrint#23]
Hi, thanks for you job with rawprint.
I trying print a bitmap image but rawprint don't. The result is a printing of lot characters.
I'm using a code like this for printing  a image.

                IPrinter printer = new Printer();

                StorageFile imagefile = await StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///Assets/image.png"));
                WriteableBitmap writeableimage;
                using (IRandomAccessStream stream = await imagefile.OpenAsync(FileAccessMode.Read))
                {
                    SoftwareBitmap softwareBitmap;
                    BitmapDecoder decoder = await BitmapDecoder.CreateAsync(stream);
                    softwareBitmap = await decoder.GetSoftwareBitmapAsync();
                    writeableimage = new WriteableBitmap(softwareBitmap.PixelWidth, softwareBitmap.PixelHeight);
                    writeableimage.SetSource(stream);

                    printer.PrintRawStream("PrinterName", stream.AsStream(), "Test", false);
                }

Please, can you help me?

**Comment by tonyedgecombe** [comment]
It won’t unless your printer supports direct image printing, I’m not aware of any printers that do.

**Comment by urbanop** [comment]
Thanks for your response Tony! Do you know or could you suggest us any alternatives in this case?
