### ISSUE TITLE
The request is not supported

### ISSUE THREAD

**Issue by Jetski5822** [frogmorecs/RawPrint#28]
Server is Windows Server 2016;

![image](https://user-images.githubusercontent.com/619530/63440081-25e45380-c427-11e9-8403-54d72b3d0175.png)

Any idea on what would be causing this?

**Comment by tonyedgecombe** [comment]
You might want to try disabling bi-directional support on the printer.

**Comment by Jetski5822** [comment]
I think thats disabled already; 

![image](https://user-images.githubusercontent.com/619530/63512732-68b43300-c4dc-11e9-9de8-5d2e89a9e7b7.png)

the printer type is `Lexmark MS810 Series XPS v4`

**Comment by tonyedgecombe** [comment]
The other thing to check is whether it is running an unusual Print Processor, ideally it should be winprint/RAW.

**Comment by Jetski5822** [comment]
All sorted... problem with printer ports!!! Thanks for your help
