### ISSUE TITLE
printing gibberish

### ISSUE THREAD

**Issue by bsdis** [frogmorecs/RawPrint#29]
Hi, I am using VS2019 and trying to use RawPrint.

When I print it using 
printer.PrintRawFile("Brother MFC-L8690CDW series Printer", @"D:\winprojects\inst.pdf", "inst.pdf");

It just prints garbage out. What could be the issue?

**Comment by tonyedgecombe** [comment]
Your printer probably doesn't support direct PDF printing.

**Comment by bsdis** [comment]
Hi @tonyedgecombe 
Thanks for your answer. I know for sure that the printer supports pdf, i have even used RawPrint with it successfully before, however I think it started going wrong when i installed visual studio 2019. Could that be a cause?

**Comment by tonyedgecombe** [comment]
I wouldn't have thought so, what version are you running?

**Comment by bsdis** [comment]
I am running dotnet 4.7.2 on a windows 10 machine using visual studio 2019. I have installed rawprint 0.5.0 via nuget. I can print pdf files without problem from browser, adobe etc. I have also been able to print pdf using rawprint before on this machine using same printer, but that was using VS 2017.

**Comment by bsdis** [comment]
When installing rawprint i did get this warning:

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Warning	NU1701	Package 'RawPrint 0.5.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.	Printtest	C:\Users\bd\source\repos\Printtest\Printtest\Printtest.csproj	1

**Comment by tonyedgecombe** [comment]
I haven't done any significant work with .Net Core yet although I would be surprised if that caused the symptoms you are getting.

**Comment by bsdis** [comment]
ok, strange...ok...at least it seems the free Spire.pdf is working so i will go with that instead then. Thanks for your help.
