### ISSUE TITLE
Duplex print

### ISSUE THREAD

**Issue by yashbajra** [frogmorecs/RawPrint#32]
How to configure RawPrint to do duplex print?
I have done following without any success
- Configured printer's setting to 2-Sided print
- Define print settings in document to be printed (it is a pdf).

Even with the changes above, I am always getting single sided print.

**Comment by tonyedgecombe** [comment]
You can't, that information is contained in the file you are printing which is passed directly to the printer without change.

**Comment by yashbajra** [comment]
Hi Tony,
When I check the pdf's properties in Abode Acrobat Reader, its DuplexMode
is configured as 'Duplex Flip Long Edge'. Still, the file is printed on
1-side only.
Screenshot attached.
[image: image.png]

**Comment by tonyedgecombe** [comment]
RawPrint sends the document to the printer unchanged, bypassing the printer driver. What's in the raw file gets written directly to the printer.
