### ISSUE TITLE
Can't print on RDP session

### ISSUE THREAD

**Issue by RWooters** [frogmorecs/RawPrint#4]
I can't seem to get the RP.exe to work in an **RDP session**. I see the print job go into the queue but nothing comes out the printer.

**Comment by tonyedgecombe** [comment]
What format is the file in?

**Comment by tonyedgecombe** [comment]
What format is the file in? It needs to be compatible with the printer so most likely PCL or PostScript depending on the printer.

**Comment by RWooters** [comment]
The file format is PCL6 and our tests show that if we print from the local PC to our printer your code works great but, if we connect on to the RDS then print to the same printer the PCL file is never printed.

So I did some googling and found the problem. Looks like it the **TS Easy Print**.
[https://support.microsoft.com/en-us/help/2827141/writeprinter-with-raw-data-fails-to-print-with-ts-easy-print](url)

So now we are going to see if we can send an XPS file with your Class.
