### ISSUE TITLE
Doesn't reflect exact number of pages printed

### ISSUE THREAD

**Issue by ahmetmert** [frogmorecs/RawPrint#8]
I am populating ZPL strings (or PCLs) into single string, convert it into stream and pass it to this method as a parameter. 
 PrintRawStream(string printer, Stream stream, string documentName, bool paused, int pagecount);

Because I know how many pages I am sending to the printer beforehand, I am passing this info as pagecount parameter individually. 

After that, I am monitoring the printjobs using Win32_PrintJob api. When I check the status of the print, I am able to retrieve correct information regarding TotalPages information however, it does not show me the correct pagesPrinted info. 
UInt32 pagesPrinted = (UInt32)prntJob.Properties["PagesPrinted"].Value;
UInt32 totalPages = (UInt32)prntJob.Properties["TotalPages"].Value;

PagesPrinted properties always return 0 no matter how many pages the printer prints. 

I don't know if it is a bug in RawPrint logic or in printer driver. Or I am doing something wrong. 
I tested this with Zebra ZT230 and HP LaserJet M604

**Comment by tonyedgecombe** [comment]
From: https://msdn.microsoft.com/en-us/library/windows/desktop/dd145020(v=vs.85).aspx

> The number of pages that have printed. This value may be zero if the print job does not contain page delimiting information.

As we print one whole file it will not contain delimiting information.

**Comment by ahmetmert** [comment]
Thank you for your response.  Actually I am sending a list of string contain PCL (PDF) using RawPrint. Everything goes fine except that I can't keep track of the number of pages printed so far. 
I modified the PagePrinter method a little bit with following and hoped to be able to monitor printjobs. But unfortunately did not work.

                for (int i = 0; i < stream.Length; i++)
                {
                    printer.StartPagePrinter();
                    WritePrinter(printer, stream[i]);
                    printer.EndPagePrinter();
                }

I used to put printcodes directly to winspool.drv using a method similar to above, and I was able to see the number of printed pages properly.
Thank you for sharing the link maybe I should look for a way adding delimeter to each page.

**Comment by tonyedgecombe** [comment]
You might be able to update the value with the win32 call [SetJob](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162978(v=vs.85).aspx)

**Comment by ahmetmert** [comment]
Hello again,
By "updating the value", If you mean setting the total number of page to the print job, your logic already does that and my modification is also able set it successfully. Anyhow, I checked SetJob method and its parameters. I used to get the information regarding the printjob with retrieving  PRINTER_INFO_2 pointer, however, I realized that I am only able to get it as long as the print job stays in the printer queue and the printjob disapears from the print queue before all the pages physically printed therefore I cannot keep track of "at what page the printer is printing" info. 

[what is printing popup](https://i.imgur.com/iTFEDj5.png)

here is an example of my case. Before I take a screen shot of this, I left one page in the printer tray and checked "Keep printed documents" settings in printer properties (otherwise printjobs disapears from the printing queue immediately).  As you can see from the image, the status of jobs are Printed (and pages 3/3 and 2/2) even though none of them hasn't completely printed. 

I know this question is out of the concept of your project but since you have a lot experience on the printers, It would be great If you can show me the way that I can learn "correct number of printed pages".

Thank you

**Comment by tonyedgecombe** [comment]
If the job has left the queue then there is nothing you can do with Windows that will help. You may be able to query the printer using SNMP to see what its status is.
