### ISSUE TITLE
Print Pdf

### ISSUE THREAD

**Issue by Cesar-Ofi** [frogmorecs/RawPrint#9]
I am printing txt files without any problem, 
now I have tried PDF 

`const string file = @"C:\Users\cesar.OFI\Downloads\19-03T067282.pdf";           
var p = new Printer();
p.PrintRawFile("Star SP500 Cutter (SP542)", file, "Document Name", false);`

and it´s printed like if I open it with Notepad:

%PDF-1.2
1 0 obj
<<
/CreationDate <FEFF0044003A00320030003100380030003200300037003100370033003900310035>
/Producer <FEFF0056006900640065006F0053006F006600740020005000440046002000470065006E0065007200610074006F007200200031002E0030>
>>
endobj
2 0 obj
<<
/Length 3 0 R
/Filter /FlateDecode
>>
stream
xœ}”Ýn›@…ï#åæ2‘l¼»üsG\!¹®Ô*7XWÛëòU}Ë¾Q78"]ÖÊZBXöù˜™s†Í[à§ÛH~ºï·7˜¾áëÉ_*XOÿèáæS$_!Ý‡‡¨¸‡âDÅíÍf‡í™…t–k¶B{gÀ>É!‹ã.Éÿç½×6SË°JøÅ€(OÃ¿á
L2«gm¾"°1B¶Ñ±/W]c™†©h0ö°gšæ¥ùú€o;`#ðK'b¸
¹D6a°˜þÄáåO6`¢9žKÜë³œ¡ªÛš³v`l÷qt(¢ü­­5àÇèxÈ@
êØò
Y_vü\rÑÎN§“ß§rÅ@k­UÇñŽ¬åõò€v££lO^#ðç»,üiçqrˆ²©.gåOCÄæÊ÷t”å-,$v/ÇZ<ÝõO÷³BO½C\ƒ(Ú¸9¬ÄmY¼Æ´E¸.Ï‡è˜3R¿ƒTãÒ±DÉóÀäÜEHsµl¹1o2
ïOÝ8ÐîºÐ³™ÏÇÎ1û5òZ³h d…ÌCgË…SX9ðÈø¯R[ŸeríÔ>²Q¯Ñ’wVˆ¨Â«1µ-² €þ$s¹iMÿhèoÞ8ÓŽBI›g.{wåàh¿Ò+„^®U% e%ëi'ÓîX/7vÀj¦µ½Ò3F¿z´j¸ôy®BÞNþQI×!h¹™-U”¢9×¬a“‡“°®¥ÒG½Ë½²EoçSnãP¾k“ò#l“Ïiöþþû'uMendstream
endobj
3 0 obj
2
endobj
4 0 obj
<<
/Type /FontDescriptor
/FontName /Courier#20New
/Flags 7
/FontBBox [-122 -680 623 1021]
/MissingWidth 600
/StemV 72
/StemH 72
/ItalicAngle 0
/CapHeight 500
/XHeight 250
/Ascent 613
/Descent -188
/Leading 0
/MaxWidth 744
/AvgWidth 600
>>
endobj
5 0 obj
<<
/Type /Font
/Subtype /TrueType
/Name /F14
/BaseFont /Courier#20New
/FontDescriptor 4 0 R
/Encoding /WinAnsiEncoding
/FirstChar 30
/LastChar 255
/Widths [600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 ]
>>
endobj
6 0 obj
<<
/Type /FontDescriptor
/FontName /Courier#20New,Bold
/Flags 16391
/FontBBox [-192 -710 702 1221]
/MissingWidth 600
/StemV 144
/StemH 144
/ItalicAngle 0
/CapHeight 500
/XHeight 250
/Ascent 633
/Descent -209
/Leading 0
/MaxWidth 894
/AvgWidth 600
>>
endobj
7 0 obj
<<
/Type /Font
/Subtype /TrueType
/Name /F15
/BaseFont /Courier#20New,Bold
/FontDescriptor 6 0 R
/Encoding /WinAnsiEncoding
/FirstChar 30
/LastChar 255
/Widths [600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 600 600 600 600 600 
600 600 600 600 600 ]
>>
endobj
8 0 obj
<<
/Type /Pages
/Count 1
/MediaBox [0 0 564 811]
/Resources 9 0 R
/Kids [10 0 R ]
>>
endobj
9 0 obj
<<
/ProcSet [/PDF/Text]
/Font << /F14 5 0 R /F15 7 0 R >>
>>
endobj
10 0 obj
<<
/Type /Page
/Parent 8 0 R
/Contents 2 0 R
>>
endobj
11 0 obj
<<
/Type /Catalog
/Pages 8 0 R
>>
endobj
xref
0 12
0000000000 65535 f
0000000010 00000 n
0000000247 00000 n
0000000946 00000 n
0000000966 00000 n
0000001239 00000 n
0000002372 00000 n
0000002656 00000 n
0000003794 00000 n
0000003903 00000 n
0000003985 00000 n
0000004056 00000 n
trailer
<<
/Size 12
/Info 1 0 R
/Root 11 0 R
>>
startxref
4112
%%EOF

**Comment by tonyedgecombe** [comment]
This is only going to work if your printer supports direct PDF printing (most don't).

**Comment by Cesar-Ofi** [comment]
Thank you,

So other formats like xlsx or docx will be printed like pdf?

**Comment by tonyedgecombe** [comment]
Yes, it assumes the file is already in a format the printer understands, usually something like PCL or PostScript.

**Comment by ahmetmert** [comment]
Hello Cesa-Ofi,
Using ghost script, you can convert your pdf into a printcode whcih you can directly send to your printer using RawPrint.
Ghost script is a standalone executable so you should call it in command line.

I am assuming that you are printing your document on an HP printer.
gswin32c -dNOPAUSE -dBATCH -sDEVICE=laserjet -sOutputFile="c:/temp/out.prn" "C:\Users\cesar.OFI\Downloads\19-03T067282.pdf"

Than you can send the file at"c:/temp/out.prn"  to your printer.

[file](https://wetransfer.com/downloads/f9e16a05bfeaaf358ce81b7dfe8c86f920180212220601/777faf732bf408737c4206eab1b110c420180212220601/a7683a)

Try to send the file (generated by ghost script) I shared, to your printer, if it works, you can use the method I suggested.

**Comment by Cesar-Ofi** [comment]
Thanks for all info

We are printing in Thermal Printer, using Samsung and Epson modes

It´s about printing tickets, so txt is good for us, but I was looking for all the possibilities and I was sending other formats

Thank you
